
name: Trgoals Bot Guncelle

on:
  schedule:
    - cron: '0 * * * *' # Her saat basi calisir
  workflow_dispatch:   # Manuel calistirma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerekli Kutuphaneler
        run: pip install requests beautifulsoup4

      - name: Botu Calistir
        run: python main.py

      - name: Kaydet ve Yukle
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add Trgoals.m3u
          git commit -m "Trgoals Liste Guncellendi: $(date)" || exit 0
          git push
